Add filtering of UniProtKB to API
unipept/unipept-api pull request #56
Opened 2024-10-04 09:02 UTC by tibvdm

Add add-hoc filtering to the pept2filtered endpoint. This is a replacement for custom databases. Instead of building different indices for different databases, the API can now perform this filtering at runtime. 

The endpoint allows filtering on:
- taxa and its children
- reference proteomes
- proteins

2024-10-04 12:28 UTC, pverscha requested changes
Looks good overall. The major comment that I have is that we should somehow inform the user that something might have failed by returning a HTTP 422 status code, together with an error message in the body of the HTTP response.

Ideally, this response reports what exactly went wrong (e.g. "Error: Invalid proteome ID xxxx provided" or "Error: Invalid NCBI taxon ID xxxx provided").

I've also tested the changes:

1. The newly added `compact` option for `pept2taxa` is working as accepted.
2. Providing a filter for `pept2filtered` is not working at this time? Maybe I'm not providing the filter in the correct way. This is the request I'm making to `/mpa/pept2filtered`:

```
{
    "peptides": [
        "TTTVPWLELR",
        "AGPVLMEPLMK",
        "TGGLPYVGTGWYR",
        "TQDATHGNSLSHR",
        "VYFTADEAKAAHEAGER",
        "GAALSQNDNMLQMPLLTPVADETWGVK",
        "QGEGDKGTMKYEEFAK",
        "MLANAEEAGYKLLDRR"
    ],
    "filter": {
        "taxa": [2]
    }
}
```

And I get an error 422 with this error message as a result: `Failed to deserialize the JSON body into the target type: no variant of enum Filter found in flattened data at line 15 column 1`.

2024-10-04 12:28 UTC, pverscha commented on api/src/helpers/filters/taxa_filter.rs
> +}
When creating a new instance of the `ProteomeFilter`, an error can be thrown if something goes wrong while retrieving information about the proteome from the UniProt API. For the taxa, maybe we should consider doing the same. In this function, we should check if all given taxa IDs are known to Unipept. If not, we need to report to the user that they provided an unknown taxon ID (using an HTTP status code 422).

2025-02-24 12:54 UTC, tibvdm commented on api/src/controllers/mpa/pept2filtered.rs
> +    };
I added some top-level error handling to get rid of the internal messages. Default behaviour for taxa/proteomes is returning an empty list when a particular ID is not found

2025-02-24 12:55 UTC, tibvdm commented
> Looks good overall. The major comment that I have is that we should somehow inform the user that something might have failed by returning a HTTP 422 status code, together with an error message in the body of the HTTP response.
> 
> Ideally, this response reports what exactly went wrong (e.g. "Error: Invalid proteome ID xxxx provided" or "Error: Invalid NCBI taxon ID xxxx provided").
> 
> I've also tested the changes:
> 
> 1. The newly added `compact` option for `pept2taxa` is working as accepted.
> 2. Providing a filter for `pept2filtered` is not working at this time? Maybe I'm not providing the filter in the correct way. This is the request I'm making to `/mpa/pept2filtered`:
> 
> ```
> {
>     "peptides": [
>         "TTTVPWLELR",
>         "AGPVLMEPLMK",
>         "TGGLPYVGTGWYR",
>         "TQDATHGNSLSHR",
>         "VYFTADEAKAAHEAGER",
>         "GAALSQNDNMLQMPLLTPVADETWGVK",
>         "QGEGDKGTMKYEEFAK",
>         "MLANAEEAGYKLLDRR"
>     ],
>     "filter": {
>         "taxa": [2]
>     }
> }
> ```
> 
> And I get an error 422 with this error message as a result: `Failed to deserialize the JSON body into the target type: no variant of enum Filter found in flattened data at line 15 column 1`.

I added an extra "filter" level to the json request body

2025-03-04 08:53 UTC, pverscha requested changes
In addition to the information provided above, I've also checked the following things that are essential to the changes made in this PR:

**Supported filters**
The new `/mpa/pept2filtered` endpoint supports the following types for filtering:
* `taxa`: Accepts a list of NCBI taxon IDs (as integers).
* `proteomes`: Accepts a list of UniProt reference proteome IDs (as strings).
* `proteins`: Accepts a list of UniProtKB accession IDs (as strings).
Note: Only one of these filters can be provided at the same time, otherwise the API will return a 422 status code. This is as expected because applying multiple filters at the same time would result in undefined behavior of the endpoint.

@tibvdm After giving it some more thought, I think it makes sense to merge the `/mpa/pept2filtered` endpoint into the existing `/mpa/pept2data` endpoint (and just remove `/mpa/pept2filtered` then. There's also a few extra minor changes that I would like to see:

* [ ] After moving the filter options to `pept2data`, the endpoint should also still work if no filters are provided. Right now, I get an HTTP 422 if I don't provide the `filter` key.
* [ ] If `1` is present in a taxa filter, no filtering should be applied (because this points to the root node in the NCBI hierarchy).

2025-03-04 12:59 UTC, pverscha approved these changes

2025-03-04 13:17 UTC, merged