taxa2lca can accept a vector of ints or a vector of strings as input
unipept/unipept-api pull request #57
Opened 2024-11-28 10:55 UTC by tibvdm

The taxa2lca endpoint previously accepted a vector of u32 as input. This PR extends this `input` field so it can also accept a vector of strings that will be parsed to integers

2024-11-28 14:03 UTC, pverscha requested changes
Thanks for the PR, I've reviewed it and it works as long as all the inputs are of the same type. So if someone enters only integers it works, or if they online provide strings it works. But whenever the data types of the input array are mixed, it doesn't work anymore and I get this error message:

```
Failed to deserialize the JSON body into the target type: input: data did not match any variant of untagged enum EitherVec at line 3 column 1
```

Could you take a look at this as well? :) Thanks!

2024-11-28 18:01 UTC, bmesuere commented
Do we want to accept mixed input? I'm not against it, but if it comes at a performance cost we should think twice about it.

2024-12-03 07:49 UTC, pverscha commented
@bmesuere Maybe not, but in that case I think the error message could be improved and should return an HTTP 422 instead :)

@tibvdm Do you think this will cause an extra performance cost? If so, we only need to update the error message.

2025-03-04 09:05 UTC, pverscha approved these changes
This is looking good. The linter was still throwing some warnings, but I have fixed these now.

2025-03-04 09:05 UTC, merged